-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.About exposing (..)

import I18Next exposing (Delims(..), Translations, customTr, t, tr)


title : Translations -> String
title translations =
    t translations "about.title"


titleCustom : Translations -> (String -> a) -> List a
titleCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "about.title" []


introduction : Translations -> String
introduction translations =
    t translations "about.introduction"


introductionCustom : Translations -> (String -> a) -> List a
introductionCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "about.introduction" []


aboutAccuracy : Translations -> String
aboutAccuracy translations =
    t translations "about.aboutAccuracy"


aboutAccuracyCustom : Translations -> (String -> a) -> List a
aboutAccuracyCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "about.aboutAccuracy" []


disclaimer : Translations -> String -> String
disclaimer translations ghRepository =
    tr translations Curly "about.disclaimer" [ ( "ghRepository", ghRepository ) ]


disclaimerCustom : Translations -> (String -> a) -> a -> List a
disclaimerCustom translations nonPlaceholderLift ghRepository =
    customTr translations Curly nonPlaceholderLift "about.disclaimer" [ ( "ghRepository", ghRepository ) ]


gitHubRepository : Translations -> String
gitHubRepository translations =
    t translations "about.gitHubRepository"


gitHubRepositoryCustom : Translations -> (String -> a) -> List a
gitHubRepositoryCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "about.gitHubRepository" []


rights : Translations -> String
rights translations =
    t translations "about.rights"


rightsCustom : Translations -> (String -> a) -> List a
rightsCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "about.rights" []


appeal : Translations -> String
appeal translations =
    t translations "about.appeal"


appealCustom : Translations -> (String -> a) -> List a
appealCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "about.appeal" []


licenseHeading : Translations -> String
licenseHeading translations =
    t translations "about.licenseHeading"


licenseHeadingCustom : Translations -> (String -> a) -> List a
licenseHeadingCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "about.licenseHeading" []


licenseBody : Translations -> String -> String
licenseBody translations copying =
    tr translations Curly "about.licenseBody" [ ( "copying", copying ) ]


licenseBodyCustom : Translations -> (String -> a) -> a -> List a
licenseBodyCustom translations nonPlaceholderLift copying =
    customTr translations Curly nonPlaceholderLift "about.licenseBody" [ ( "copying", copying ) ]


links : Translations -> String
links translations =
    t translations "about.links"


linksCustom : Translations -> (String -> a) -> List a
linksCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "about.links" []
