-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Event exposing (..)

import I18Next exposing (Delims(..), Translations, customTr, t, tr)


timeWithEta : Translations -> String -> String -> String
timeWithEta translations time eta =
    tr translations Curly "event.timeWithEta" [ ( "time", time ), ( "eta", eta ) ]


timeWithEtaCustom : Translations -> (String -> a) -> a -> a -> List a
timeWithEtaCustom translations nonPlaceholderLift time eta =
    customTr translations Curly nonPlaceholderLift "event.timeWithEta" [ ( "time", time ), ( "eta", eta ) ]


due : Translations -> String -> String
due translations duration =
    tr translations Curly "event.due" [ ( "duration", duration ) ]


dueCustom : Translations -> (String -> a) -> a -> List a
dueCustom translations nonPlaceholderLift duration =
    customTr translations Curly nonPlaceholderLift "event.due" [ ( "duration", duration ) ]


startedAt : Translations -> String -> String
startedAt translations time =
    tr translations Curly "event.startedAt" [ ( "time", time ) ]


startedAtCustom : Translations -> (String -> a) -> a -> List a
startedAtCustom translations nonPlaceholderLift time =
    customTr translations Curly nonPlaceholderLift "event.startedAt" [ ( "time", time ) ]


uploadedAt : Translations -> String -> String
uploadedAt translations time =
    tr translations Curly "event.uploadedAt" [ ( "time", time ) ]


uploadedAtCustom : Translations -> (String -> a) -> a -> List a
uploadedAtCustom translations nonPlaceholderLift time =
    customTr translations Curly nonPlaceholderLift "event.uploadedAt" [ ( "time", time ) ]
