-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Help exposing (..)

import I18Next exposing (Delims(..), Translations, customTr, t, tr)


title : Translations -> String
title translations =
    t translations "help.title"


titleCustom : Translations -> (String -> a) -> List a
titleCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "help.title" []


kbdN : Translations -> String
kbdN translations =
    t translations "help.kbdN"


kbdNCustom : Translations -> (String -> a) -> List a
kbdNCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "help.kbdN" []


kbdS : Translations -> String
kbdS translations =
    t translations "help.kbdS"


kbdSCustom : Translations -> (String -> a) -> List a
kbdSCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "help.kbdS" []


kbdX : Translations -> String
kbdX translations =
    t translations "help.kbdX"


kbdXCustom : Translations -> (String -> a) -> List a
kbdXCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "help.kbdX" []


kbdDigit : Translations -> String
kbdDigit translations =
    t translations "help.kbdDigit"


kbdDigitCustom : Translations -> (String -> a) -> List a
kbdDigitCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "help.kbdDigit" []


kbdSDigit : Translations -> String
kbdSDigit translations =
    t translations "help.kbdSDigit"


kbdSDigitCustom : Translations -> (String -> a) -> List a
kbdSDigitCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "help.kbdSDigit" []


kbd0 : Translations -> String
kbd0 translations =
    t translations "help.kbd0"


kbd0Custom : Translations -> (String -> a) -> List a
kbd0Custom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "help.kbd0" []


kbdS0 : Translations -> String
kbdS0 translations =
    t translations "help.kbdS0"


kbdS0Custom : Translations -> (String -> a) -> List a
kbdS0Custom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "help.kbdS0" []


kbdQuestion : Translations -> String
kbdQuestion translations =
    t translations "help.kbdQuestion"


kbdQuestionCustom : Translations -> (String -> a) -> List a
kbdQuestionCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "help.kbdQuestion" []
