-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Share exposing (..)

import I18Next exposing (Delims(..), Translations, customTr, t, tr)


share : Translations -> String
share translations =
    t translations "share.share"


shareCustom : Translations -> (String -> a) -> List a
shareCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "share.share" []


copyTitleAndUrl : Translations -> String
copyTitleAndUrl translations =
    t translations "share.copyTitleAndUrl"


copyTitleAndUrlCustom : Translations -> (String -> a) -> List a
copyTitleAndUrlCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "share.copyTitleAndUrl" []


copyTimestamp : Translations -> String
copyTimestamp translations =
    t translations "share.copyTimestamp"


copyTimestampCustom : Translations -> (String -> a) -> List a
copyTimestampCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "share.copyTimestamp" []


shareVia : Translations -> String
shareVia translations =
    t translations "share.shareVia"


shareViaCustom : Translations -> (String -> a) -> List a
shareViaCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "share.shareVia" []
