-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Status exposing (..)

import I18Next exposing (Delims(..), Translations, customTr, t, tr)


clearFeedFilter : Translations -> String
clearFeedFilter translations =
    t translations "status.clearFeedFilter"


clearFeedFilterCustom : Translations -> (String -> a) -> List a
clearFeedFilterCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "status.clearFeedFilter" []


clearFilter : Translations -> String
clearFilter translations =
    t translations "status.clearFilter"


clearFilterCustom : Translations -> (String -> a) -> List a
clearFilterCustom translations nonPlaceholderLift =
    customTr translations Curly nonPlaceholderLift "status.clearFilter" []


showingFeed : Translations -> String -> String
showingFeed translations title =
    tr translations Curly "status.showingFeed" [ ( "title", title ) ]


showingFeedCustom : Translations -> (String -> a) -> a -> List a
showingFeedCustom translations nonPlaceholderLift title =
    customTr translations Curly nonPlaceholderLift "status.showingFeed" [ ( "title", title ) ]


hidingFeed : Translations -> String -> String
hidingFeed translations title =
    tr translations Curly "status.hidingFeed" [ ( "title", title ) ]


hidingFeedCustom : Translations -> (String -> a) -> a -> List a
hidingFeedCustom translations nonPlaceholderLift title =
    customTr translations Curly nonPlaceholderLift "status.hidingFeed" [ ( "title", title ) ]


showingOnly : Translations -> String -> String
showingOnly translations title =
    tr translations Curly "status.showingOnly" [ ( "title", title ) ]


showingOnlyCustom : Translations -> (String -> a) -> a -> List a
showingOnlyCustom translations nonPlaceholderLift title =
    customTr translations Curly nonPlaceholderLift "status.showingOnly" [ ( "title", title ) ]
