-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Event.Description exposing (..)

import I18Next exposing (Delims(..), Translations, customTr, t, tr)


scheduledLive : Translations -> String -> String -> String
scheduledLive translations members beginsIn =
    tr translations Curly "event.description.scheduledLive" [ ( "members", members ), ( "beginsIn", beginsIn ) ]


scheduledLiveCustom : Translations -> (String -> a) -> a -> a -> List a
scheduledLiveCustom translations nonPlaceholderLift members beginsIn =
    customTr translations Curly nonPlaceholderLift "event.description.scheduledLive" [ ( "members", members ), ( "beginsIn", beginsIn ) ]


startedLive : Translations -> String -> String -> String
startedLive translations members time =
    tr translations Curly "event.description.startedLive" [ ( "members", members ), ( "time", time ) ]


startedLiveCustom : Translations -> (String -> a) -> a -> a -> List a
startedLiveCustom translations nonPlaceholderLift members time =
    customTr translations Curly nonPlaceholderLift "event.description.startedLive" [ ( "members", members ), ( "time", time ) ]


video : Translations -> String -> String -> String
video translations members time =
    tr translations Curly "event.description.video" [ ( "members", members ), ( "time", time ) ]


videoCustom : Translations -> (String -> a) -> a -> a -> List a
videoCustom translations nonPlaceholderLift members time =
    customTr translations Curly nonPlaceholderLift "event.description.video" [ ( "members", members ), ( "time", time ) ]


twoMembers : Translations -> String -> String -> String
twoMembers translations author member =
    tr translations Curly "event.description.twoMembers" [ ( "author", author ), ( "member", member ) ]


twoMembersCustom : Translations -> (String -> a) -> a -> a -> List a
twoMembersCustom translations nonPlaceholderLift author member =
    customTr translations Curly nonPlaceholderLift "event.description.twoMembers" [ ( "author", author ), ( "member", member ) ]


moreThanTwoMembers : Translations -> String -> String -> String
moreThanTwoMembers translations author n =
    tr translations Curly "event.description.moreThanTwoMembers" [ ( "author", author ), ( "n", n ) ]


moreThanTwoMembersCustom : Translations -> (String -> a) -> a -> a -> List a
moreThanTwoMembersCustom translations nonPlaceholderLift author n =
    customTr translations Curly nonPlaceholderLift "event.description.moreThanTwoMembers" [ ( "author", author ), ( "n", n ) ]
