-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Event.Description exposing (..)

import I18Next exposing (Delims(..), Translations, customTr, t, tr)


scheduledLive : Translations -> String -> String -> String
scheduledLive translations members eta =
    tr translations Curly "event.description.scheduledLive" [ ( "members", members ), ( "eta", eta ) ]


scheduledLiveCustom : Translations -> (String -> a) -> a -> a -> List a
scheduledLiveCustom translations nonPlaceholderLift members eta =
    customTr translations Curly nonPlaceholderLift "event.description.scheduledLive" [ ( "members", members ), ( "eta", eta ) ]


ongoingLive : Translations -> String -> String -> String
ongoingLive translations members eta =
    tr translations Curly "event.description.ongoingLive" [ ( "members", members ), ( "eta", eta ) ]


ongoingLiveCustom : Translations -> (String -> a) -> a -> a -> List a
ongoingLiveCustom translations nonPlaceholderLift members eta =
    customTr translations Curly nonPlaceholderLift "event.description.ongoingLive" [ ( "members", members ), ( "eta", eta ) ]


endedLive : Translations -> String -> String -> String -> String
endedLive translations members time duration =
    tr translations Curly "event.description.endedLive" [ ( "members", members ), ( "time", time ), ( "duration", duration ) ]


endedLiveCustom : Translations -> (String -> a) -> a -> a -> a -> List a
endedLiveCustom translations nonPlaceholderLift members time duration =
    customTr translations Curly nonPlaceholderLift "event.description.endedLive" [ ( "members", members ), ( "time", time ), ( "duration", duration ) ]


video : Translations -> String -> String -> String -> String
video translations members time duration =
    tr translations Curly "event.description.video" [ ( "members", members ), ( "time", time ), ( "duration", duration ) ]


videoCustom : Translations -> (String -> a) -> a -> a -> a -> List a
videoCustom translations nonPlaceholderLift members time duration =
    customTr translations Curly nonPlaceholderLift "event.description.video" [ ( "members", members ), ( "time", time ), ( "duration", duration ) ]


twoMembers : Translations -> String -> String -> String
twoMembers translations author member =
    tr translations Curly "event.description.twoMembers" [ ( "author", author ), ( "member", member ) ]


twoMembersCustom : Translations -> (String -> a) -> a -> a -> List a
twoMembersCustom translations nonPlaceholderLift author member =
    customTr translations Curly nonPlaceholderLift "event.description.twoMembers" [ ( "author", author ), ( "member", member ) ]


moreThanTwoMembers : Translations -> String -> String -> String
moreThanTwoMembers translations author n =
    tr translations Curly "event.description.moreThanTwoMembers" [ ( "author", author ), ( "n", n ) ]


moreThanTwoMembersCustom : Translations -> (String -> a) -> a -> a -> List a
moreThanTwoMembersCustom translations nonPlaceholderLift author n =
    customTr translations Curly nonPlaceholderLift "event.description.moreThanTwoMembers" [ ( "author", author ), ( "n", n ) ]
