export default [
	{
		id: "yt:channel:UCEOugXOAfa-HRmRjKbH8z3Q",
		title: "けものフレンズプロジェクト公式",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/qXk8L8kI7-cGKXCRRdEy3Td9fOZ7bjxg5AxX7Zc3zxzHQXy9d8PjcFzM8p_JOOnBu7Ay0Zdy5g=s60",
	},
	{
		id: "yt:channel:UCrMKWvQuyFL1dckG2RLInDQ",
		title: "パークスタッフ / Park Staff",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/phX9Lg0o-onftJgEhuwDMqSEP5CUbTu0nBlVnPF9HqF114s6k1Yd411zuWz8gscqWByzDmmYhQ=s60",
	},
	{
		id: "yt:channel:UCmYO-WfY7Tasry4D1YB4LJw",
		title: "フンボルトペンギン / Humboldt Penguin",
		lang: "ja",
		icon: "https://yt3.ggpht.com/ytc/AKedOLSr75ivVQI4bHcaoMOaYxPjbRnL3-2VCSNuHbJ-=s60",
	},
	{
		id: "yt:channel:UCMpw36mXEu3SLsqdrJxUKNA",
		title: "シマハイイロギツネ / Island Fox",
		lang: "ja",
		icon: "https://yt3.ggpht.com/2ohbFqFqLbEw66rWMhTjb-wpa5X9APonb1KZiiBJbmGcS69yKUwtmLSHfhPUSF4snFp1O9r_=s60",
	},
	{
		id: "yt:channel:UCabMjG8p6G5xLkPJgEoTnDg",
		title: "コヨーテ / Coyote",
		lang: "en",
		icon: "https://yt3.ggpht.com/VwLc2w11lh_JlrsDB9P4OvBJpqaoAZdS08gqQx7vtJ5-4DjsEiP5Un6xmT0q8VE6zr8uXYEnTqg=s60",
	},
	{
		id: "yt:channel:UCdNBhcAohYjXlUVYsz8X2KQ",
		title: "ダイアウルフ / Dire Wolf",
		lang: "ja",
		icon: "https://yt3.ggpht.com/yJUytRAl-MwBrGmIXMdctRgcNuAborghz1SGt2o6KDewrB1aP6saZLdX9HWBPdF5JEutZ6aBKNY=s60",
	},
	{
		id: "yt:channel:UCxm7yNjJsSvyvcG96-Cvmpw",
		title: "カラカル / Caracal",
		lang: "ja",
		icon: "https://yt3.ggpht.com/PfYRtTGfYRkpluFsqAjYgSERbvu7wQ-pNpRARUeSTvka1pa-t3rFgb4DhxNuhDikmz-BP8WLgw=s60",
	},
	{
		id: "yt:channel:UCNObi6xvj6QeZ0g7BhAbF7w",
		title: "ジェネット / Large-spotted Genet",
		lang: "ja",
		icon: "https://yt3.ggpht.com/F6Ohg12s3EWoWndeHE75L9t6SSCUz3fldo5eXuvWKgnAIp6cJtBgKu2bcjLUEo2tdzO4hlIy=s60",
	},
	{
		id: "yt:channel:UCYa58DdXGAGMJQHqTxi-isA",
		title: "ジョフロイネコ / Geoffroy’s Cat",
		lang: "ja",
		icon: "https://yt3.ggpht.com/qC2D9mBgEcXQWqzf7mG0g5T5JTa_-H8OjDpOvcYLrm1vrIboL52ytoGFvZTUoSjJaCQ94wo0XQ=s60",
	},
	{
		id: "yt:channel:UCnyE-wD1pE2GZOxA6OHjW9g",
		title: "ウサギコウモリ / Brown Long-eared Bat",
		lang: "ja",
		icon: "https://yt3.ggpht.com/xmwgkDPO8SWQvm_XgGV-hwwFD3kHbOuxSW01FylectI7NyeEtafp_GXRmbWaa9sMJp6PeakT=s60",
	},
	{
		id: "yt:channel:UCtJSUW-5FnwfaivXpluABWA",
		title: "ジャングルキャット / Jungle Cat",
		lang: "ja",
		icon: "https://yt3.ggpht.com/SwzdmxFAnvpDq7mnKTFmIILkQ-nsEfWol9ALoLJZ4gWUG0xb1Be2lf6jUiOaGgXFYxQXcbdH9w=s60",
	},
	{
		id: "yt:channel:UCKob71cjOlyYF5bgvtGuNKQ",
		title: "シマリス / Siberian Chipmunk",
		lang: "ja",
		icon: "https://yt3.ggpht.com/x6ftrixLrF0GGGBnkDwWQEjkUqswTuUGrxBZLvRY47-9woj9B7Q9tfkY19yZWiYYpWW6OcqB2Q=s60",
	},
	{
		id: "yt:channel:UCEcMIuGR8WO2TwL9XIpjKtw",
		title: "ケープペンギン / African Penguin",
		lang: "ja",
		icon: "https://yt3.ggpht.com/ytc/AKedOLSiSzCCyj5TBipvNgNcz0NrPZbvJZmZQU9JUFE-=s60",
	},
];
