export default [
	{
		id: "yt:channel:UCEOugXOAfa-HRmRjKbH8z3Q",
		title: "けものフレンズプロジェクト公式",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/qXk8L8kI7-cGKXCRRdEy3Td9fOZ7bjxg5AxX7Zc3zxzHQXy9d8PjcFzM8p_JOOnBu7Ay0Zdy5g=s60",
	},
	{
		id: "yt:channel:UCrMKWvQuyFL1dckG2RLInDQ",
		title: "パークスタッフ / Park Staff",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/phX9Lg0o-onftJgEhuwDMqSEP5CUbTu0nBlVnPF9HqF114s6k1Yd411zuWz8gscqWByzDmmYhQ=s60",
	},
	{
		id: "yt:channel:UCmYO-WfY7Tasry4D1YB4LJw",
		title: "フンボルトペンギン / Humboldt Penguin",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/ytc/AIdro_nucgOj565yWEa2KXJsE7zzQrjhYG0h6bphYbUzSx7p1Q=s60",
	},
	{
		id: "yt:channel:UCMpw36mXEu3SLsqdrJxUKNA",
		title: "シマハイイロギツネ / Island Fox",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/2ohbFqFqLbEw66rWMhTjb-wpa5X9APonb1KZiiBJbmGcS69yKUwtmLSHfhPUSF4snFp1O9r_=s60",
	},
	{
		id: "yt:channel:UCabMjG8p6G5xLkPJgEoTnDg",
		title: "コヨーテ / Coyote",
		lang: "en",
		icon: "https://yt3.googleusercontent.com/-jp0xO_hk95EgFm1z4_EZOpXJRM0B8auEwifKeSEHZx09OHly9ygQHHIk3TTkuMZ6zLhhk0hXA=s60",
	},
	{
		id: "yt:channel:UCdNBhcAohYjXlUVYsz8X2KQ",
		title: "ダイアウルフ / Dire Wolf",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/B_QAdGj-_LGHj7rmJdLxVnyc4DvznyqnpEfnbstrExQA_eS7alt4v1FoM1e7HpEdq65QdRj8Coo=s60",
	},
	{
		id: "yt:channel:UCxm7yNjJsSvyvcG96-Cvmpw",
		title: "カラカル / Caracal",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/6H0SlGWB0fpx3YR3wMkYaG9QQsEhkFUgcx4DodT-_cDEXLdEHpqfxg6XK5U-qJXrkioWTI9YDg=s60",
	},
	{
		id: "yt:channel:UCNObi6xvj6QeZ0g7BhAbF7w",
		title: "ジェネット / Large-spotted Genet",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/F6Ohg12s3EWoWndeHE75L9t6SSCUz3fldo5eXuvWKgnAIp6cJtBgKu2bcjLUEo2tdzO4hlIy=s60",
	},
	{
		id: "yt:channel:UCYa58DdXGAGMJQHqTxi-isA",
		title: "ジョフロイネコ / Geoffroy’s Cat",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/9euqc6PdKxTfTJTOTDvuNU9R6zY9Vwjaj8IB3PaD0U7VtX_aMB9-w06t3vTaCH_onX9Rj954vQ=s60",
	},
	{
		id: "yt:channel:UCnyE-wD1pE2GZOxA6OHjW9g",
		title: "ウサギコウモリ / Brown Long-eared Bat",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/lOupphnIz6eL4UuzmA8GkM_n5vZdyZkd-MQ2PiUY4BhMKIZUySS_jFPcwvehVLhOKHmQ8CG1=s60",
	},
	{
		id: "yt:channel:UCtJSUW-5FnwfaivXpluABWA",
		title: "ジャングルキャット / Jungle Cat",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/DoY1-B-GiXKzKMFVyqDs61vkLuoaruCs-TjJKtThdX18Hcqpq29HyqI8SWTDafLTJLZQCRoSlQ=s60",
	},
	{
		id: "yt:channel:UCKob71cjOlyYF5bgvtGuNKQ",
		title: "シマリス / Siberian Chipmunk",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/AEo8xi-6_WDxJt3s0Zd-5YcibmtziIxJ1Nkx_pJATh4yDj3Q0I-_RZl26klky-JIeKUZIhp3VQ=s60",
	},
	{
		id: "yt:channel:UCEcMIuGR8WO2TwL9XIpjKtw",
		title: "ケープペンギン / African Penguin",
		lang: "ja",
		icon: "https://yt3.googleusercontent.com/ytc/AIdro_lkvVhwNCvG354xLsHirSmluolfqcyJrz0MkG6IVtywBQ=s60",
	},
];
