name: Build
on:
  push:
    branches:
      - main
    paths:
      - Makefile
      - elm.json
      - 'src/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/heads/gh-pages
      - name: Setup Elm
        uses: mpizenberg/elm-tooling-action@e8d4d23a71ba5993d67ca18531438991e3b4e28d
        with:
          cache-key: elm-home-${{ hashFiles('elm.json') }}
      - name: Install dependencies
        run: |
          pip install brotli fonttools
          npm install --location=global elm-optimize-level-2
          npm install --location=global uglify-js
      - name: Build
        run: |
          git fetch --no-tags --depth=1 origin refs/heads/main
          git reset FETCH_HEAD
          git checkout .
          git add data/ feed/ || true

          rm -- *.woff2 || true
          make --always-make ELM_MAKE=elm-optimize-level-2 ELMFLAGS= app.js fonts
          git add -- app.js *.woff2 \*.woff2
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(ci): squash & build'
          branch: gh-pages
          file_pattern: ''
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          push_options: '--force'
