name: Build
on:
  push:
    branches:
      - main
    paths:
      - Makefile
      - elm.json
      - 'public/**'
      - 'src/**'
      - 'vite.config.js'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - name: Setup Elm
        uses: mpizenberg/elm-tooling-action@v1.7
        with:
          cache-key: elm-home-${{ hashFiles('elm.json') }}
      - name: Install dependencies
        run: |
          pip install brotli fonttools
      - name: Build
        run: |
          rm -r docs/ || true
          rm public/*.woff2 || true
          make --always-make fonts docs/index.html
      - uses: actions/upload-artifact@v4
        with:
          path: |
            docs/
          if-no-files-found: error
  push:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: docs
      - run: |
          git add docs/
          git fetch --no-tags --depth=1 origin refs/heads/gh-pages
          git checkout FETCH_HEAD data/ || true
          git checkout FETCH_HEAD docs/feed/ || true
          git switch -c gh-pages
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(ci): squash & build'
          branch: gh-pages
          file_pattern: ''
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          push_options: '--force'
