name: Update GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Update GitHub Pages
        uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7
        with:
          workflow: 3609993
          repo: U-cauda-elongata/u-cauda-elongata.github.io
          ref: refs/heads/master
          token: ${{ secrets.PERSONAL_TOKEN }}
