name: Update GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: 3609993
          repo: U-cauda-elongata/u-cauda-elongata.github.io
          token: ${{ secrets.PERSONAL_TOKEN }}
