name: Update feeds

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch feeds
        run: |
          for ytc in \
            UCEOugXOAfa-HRmRjKbH8z3Q \
            UCEcMIuGR8WO2TwL9XIpjKtw \
            UCmYO-WfY7Tasry4D1YB4LJw \
            UCMpw36mXEu3SLsqdrJxUKNA \
            UCabMjG8p6G5xLkPJgEoTnDg \
            UCdNBhcAohYjXlUVYsz8X2KQ
          do
            curl -fLSs "https://www.youtube.com/feeds/videos.xml?channel_id=$ytc" -o "$ytc.xml"
            git add "$ytc.xml"
          done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update feeds
      - name: Update GitHub Pages
        uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7
        with:
          workflow: 3609993
          repo: U-cauda-elongata/u-cauda-elongata.github.io
          ref: refs/heads/master
          token: ${{ secrets.PERSONAL_TOKEN }}
